project_name: crossplanereleaser
builds:
  - id: crossplanereleaser
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      # - darwin
    goarch:
      - amd64
      # - arm64
    main: ./cmd/crossplanereleaser

archives:
  - id: crossplanereleaser
    format: tar.gz
    name_template: '{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}'
    builds:
      - crossplanereleaser
    wrap_in_directory: true
    strip_parent_binary_folder: true
    files:
      - LICENSE.txt
      - README.md

checksum:
  algorithm: sha256
  name_template: 'checksums.txt'
  ids:
    - crossplanereleaser
