name: release

on:
  push:
    tags:
      - "*"

permissions:
  contents: write

env:
  GO_VERSION: '1.21.6'
  GOLANGCI_VERSION: 'v1.55.2'
  GORELEASER_VERSION: 'v1.23.0'

jobs:
  goreleaser:
    needs:
      - build
      - lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: ${{ env.GORELEASER_VERSION }}
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish artifacts to Github
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist
